# @package _global_
model:
  name: SB-DS7B-alpha-2
  model_size: 7B
  mode: eval
  path: /home/zsj/ACL-ARR-Jan-Rebuttal/OThink-R1/models/SB_DS7B_alpha_2
  inference:
    tensor_parallel_size: 1
    enable_prefix_caching: True
    gpu_memory_utilization: 0.95
    temperature: 0.6
    top_p: 0.95
    max_tokens: 16384
    skip_special_tokens: True
    repetition_penalty: 1.0
